name: Build and Deploy Eleventy to Cloudways

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_DIR: /home/master/applications/jkkppyvmpr/public_html/eon/eleventy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Eleventy site
        run: npx @11ty/eleventy --output=_site

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 128.199.22.182 >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz --delete _site/ master_znavuzmyxy@128.199.22.182:$APP_DIR/
